import { Predeploy } from '@/types';

// https://developer.arbitrum.io/useful-addresses#arbitrum-precompiles-l2-same-on-all-arb-chains
export const predeploys: Predeploy[] = [
  {
    address: '0x5288c571Fd7aD117beA99bF60FE0846C4E84F933',
    name: 'L2 Gateway Router',
    description:
      'Handles withdrawals from Ethereum into Arbitrum. Tokens are routed to their appropriate L2 gateway (Router itself also conforms to the Gateway interface).',
    abi: [
      'constructor(address _logic, address admin_, bytes _data) payable',
      'event AdminChanged(address previousAdmin, address newAdmin)',
      'event Upgraded(address indexed implementation)',
      'fallback()',
      'function admin() returns (address admin_)',
      'function changeAdmin(address newAdmin)',
      'function implementation() returns (address implementation_)',
      'function upgradeTo(address newImplementation)',
      'function upgradeToAndCall(address newImplementation, bytes data) payable',
      'receive() external payable',
    ],
    deprecated: false,
    references: ['https://developer.arbitrum.io/for-devs/useful-addresses'],
  },
  {
    address: '0x09e9222E96E7B4AE2a407B98d48e330053351EEe',
    name: 'L2 ERC20 Gateway',
    description:
      "Initiates Arbitrum to Ethereum ERC20 transfers, which are forwarded to the token's L2 Gateway to communicate with its corresponding L1 Gateway.",
    abi: [
      'constructor(address _logic, address admin_, bytes _data) payable',
      'event AdminChanged(address previousAdmin, address newAdmin)',
      'event Upgraded(address indexed implementation)',
      'fallback()',
      'function admin() returns (address admin_)',
      'function changeAdmin(address newAdmin)',
      'function implementation() returns (address implementation_)',
      'function upgradeTo(address newImplementation)',
      'function upgradeToAndCall(address newImplementation, bytes data) payable',
      'receive() external payable',
    ],
    deprecated: false,
    references: ['https://developer.arbitrum.io/for-devs/useful-addresses'],
  },
  {
    address: '0x096760F208390250649E3e8763348E783AEF5562',
    name: 'L2 Arb-Custom Gateway',
    description:
      'Allows to transfer of custom tokens from Arbitrum to Ethereum, which are forwarded to the L2 Gateway to communicate with its corresponding L1 Gateway.',
    abi: [
      'constructor(address _logic, address admin_, bytes _data) payable',
      'event AdminChanged(address previousAdmin, address newAdmin)',
      'event Upgraded(address indexed implementation)',
      'fallback()',
      'function admin() returns (address admin_)',
      'function changeAdmin(address newAdmin)',
      'function implementation() returns (address implementation_)',
      'function upgradeTo(address newImplementation)',
      'function upgradeToAndCall(address newImplementation, bytes data) payable',
      'receive() external payable',
    ],
    deprecated: false,
    references: ['https://developer.arbitrum.io/for-devs/useful-addresses'],
  },
  {
    address: '0x6c411aD3E74De3E7Bd422b94A27770f5B86C623B',
    name: 'L2 Weth Gateway',
    description:
      "Handles Arbitrum to Ethereum transfers of WETH by unwrapping the Ether and re-wrapping it on Ethereum, ensuring that all WETH tokens are always fully collateralized on the layer it's transferred to.",
    abi: [
      'constructor(address _logic, address admin_, bytes _data) payable',
      'event AdminChanged(address previousAdmin, address newAdmin)',
      'event Upgraded(address indexed implementation)',
      'fallback()',
      'function admin() returns (address admin_)',
      'function changeAdmin(address newAdmin)',
      'function implementation() returns (address implementation_)',
      'function upgradeTo(address newImplementation)',
      'function upgradeToAndCall(address newImplementation, bytes data) payable',
      'receive() external payable',
    ],
    deprecated: false,
    references: ['https://developer.arbitrum.io/for-devs/useful-addresses'],
  },
  {
    address: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
    name: 'L2 Weth',
    description:
      'Wrapped Ether contract on Arbitrum, which is an ERC-20 token that represents 1 Ether.',
    abi: [
      'constructor(address _logic, address admin_, bytes _data) payable',
      'event AdminChanged(address previousAdmin, address newAdmin)',
      'event Upgraded(address indexed implementation)',
      'fallback()',
      'function admin() returns (address admin_)',
      'function changeAdmin(address newAdmin)',
      'function implementation() returns (address implementation_)',
      'function upgradeTo(address newImplementation)',
      'function upgradeToAndCall(address newImplementation, bytes data) payable',
      'receive() external payable',
    ],
    deprecated: false,
    references: ['https://developer.arbitrum.io/for-devs/useful-addresses'],
  },
  {
    address: '0xd570aCE65C43af47101fC6250FD6fC63D1c22a86',
    name: 'L2 Proxy Admin',
    description: 'The owner of all of the Arbitrum proxy contracts set at the predeploys.',
    abi: [
      'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
      'function changeProxyAdmin(address proxy, address newAdmin)',
      'function getProxyAdmin(address proxy) view returns (address)',
      'function getProxyImplementation(address proxy) view returns (address)',
      'function owner() view returns (address)',
      'function renounceOwnership()',
      'function transferOwnership(address newOwner)',
      'function upgrade(address proxy, address implementation)',
      'function upgradeAndCall(address proxy, address implementation, bytes data) payable',
    ],
    deprecated: false,
    references: ['https://developer.arbitrum.io/for-devs/useful-addresses'],
  },

  {
    address: '0x0000000000000000000000000000000000000065',
    name: 'ArbInfo',
    description: 'Provides the ability to lookup basic info about accounts and contracts.',
    abi: [
      'function getBalance(address account) view returns (uint256)',
      'function getCode(address account) view returns (bytes)',
    ],
    deprecated: false,
    references: ['https://developer.arbitrum.io/for-devs/useful-addresses'],
  },
];
